name: 'Deploy WebApp to Sakura AppRun'
description: 'Build and deploy web applications to Sakura AppRun'
author: 'templain'
branding:
  icon: 'cloud'
  color: 'purple'

inputs:
  sakura-api-key:
    description: 'Sakura Cloud API Key'
    required: true
  sakura-api-secret:
    description: 'Sakura Cloud API Secret'
    required: true
  container-registry:
    description: 'Container registry URL (e.g., myregistry.sakuracr.jp)'
    required: true
  container-registry-user:
    description: 'Container registry username'
    required: true
  container-registry-password:
    description: 'Container registry password'
    required: true
  app-name:
    description: 'Application name (defaults to repository name)'
    required: false
    default: ''
  port:
    description: 'Application port'
    required: false
    default: '3000'
  max-cpu:
    description: 'Maximum CPU (e.g., "1", "0.5")'
    required: false
    default: '0.4'
  max-memory:
    description: 'Maximum memory (e.g., "512Mi", "1Gi")'
    required: false
    default: '256Mi'
  timeout-seconds:
    description: 'Request timeout in seconds'
    required: false
    default: '300'
  database-url:
    description: 'Database URL'
    required: false
    default: ''
  auth-callback-url:
    description: 'Auth Callback URL'
    required: false
    default: ''
  google-client-id:
    description: 'Google Client ID'
    required: false
    default: ''
  google-client-secret:
    description: 'Google Client Secret'
    required: false
    default: ''
  github-client-id:
    description: 'GitHub Client ID'
    required: false
    default: ''
  github-client-secret:
    description: 'GitHub Client Secret'
    required: false
    default: ''
  facebook-client-id:
    description: 'FaceBook Client ID'
    required: false
    default: ''
  facebook-client-secret:
    description: 'Facebook Client Secret'
    required: false
    default: ''
    
outputs:
  public-url:
    description: 'The public URL of the deployed application'
    value: ${{ steps.deploy.outputs.public-url }}
  app-id:
    description: 'The AppRun application ID'
    value: ${{ steps.deploy.outputs.app-id }}

runs:
  using: 'composite'
  steps:
    - name: Set app name
      id: app-name
      shell: bash
      run: |
        APP_NAME="${{ inputs.app-name }}"
        if [ -z "$APP_NAME" ]; then
          APP_NAME="${{ github.event.repository.name }}"
        fi
        echo "name=${APP_NAME}" >> $GITHUB_OUTPUT
        
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.container-registry }}
        username: ${{ inputs.container-registry-user }}
        password: ${{ inputs.container-registry-password }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          ${{ inputs.container-registry }}/${{ steps.app-name.outputs.name }}:latest
          ${{ inputs.container-registry }}/${{ steps.app-name.outputs.name }}:${{ github.sha }}
        build-args: |
          PORT=${{ inputs.port }}
        provenance: false
        
    - name: Deploy to AppRun
      id: deploy
      shell: bash
      run: |
        # Create auth header
        AUTH=$(echo -n "${{ inputs.sakura-api-key }}:${{ inputs.sakura-api-secret }}" | base64 | tr -d '\n')
        
        # Build environment variables array
        ENV_VARS="[]"
        if [ -n "${{ inputs.database-url }}" ]; then
          ENV_VARS=$(echo "$ENV_VARS" | jq '. + [{"key": "DATABASE_URL", "value": "${{ inputs.database-url }}"}]')
        fi
        if [ -n "${{ inputs.auth-callback-url }}" ]; then
          ENV_VARS=$(echo "$ENV_VARS" | jq '. + [{"key": "AUTH_CALLBACK_URL", "value": "${{ inputs.auth-callback-url }}"}]')
        fi
        if [ -n "${{ inputs.google-client-id }}" ]; then
          ENV_VARS=$(echo "$ENV_VARS" | jq '. + [{"key": "GOOGLE_CLIENT_ID", "value": "${{ inputs.google-client-id }}"}]')
        fi
        if [ -n "${{ inputs.google-client-secret }}" ]; then
          ENV_VARS=$(echo "$ENV_VARS" | jq '. + [{"key": "GOOGLE_CLIENT_SECRET", "value": "${{ inputs.google-client-secret }}"}]')
        fi
        if [ -n "${{ inputs.github-client-id }}" ]; then
          ENV_VARS=$(echo "$ENV_VARS" | jq '. + [{"key": "GITHUB_CLIENT_ID", "value": "${{ inputs.github-client-id }}"}]')
        fi
        if [ -n "${{ inputs.github-client-secret }}" ]; then
          ENV_VARS=$(echo "$ENV_VARS" | jq '. + [{"key": "GITHUB_CLIENT_SECRET", "value": "${{ inputs.github-client-secret }}"}]')
        fi
        if [ -n "${{ inputs.facebook-client-id }}" ]; then
          ENV_VARS=$(echo "$ENV_VARS" | jq '. + [{"key": "FACEBOOK_CLIENT_ID", "value": "${{ inputs.facebook-client-id }}"}]')
        fi
        if [ -n "${{ inputs.facebook-client-secret }}" ]; then
          ENV_VARS=$(echo "$ENV_VARS" | jq '. + [{"key": "FACEBOOK_CLIENT_SECRET", "value": "${{ inputs.facebook-client-secret }}"}]')
        fi
        
        # Create request body with jq
        REQUEST_BODY=$(jq -n \
          --arg name "${{ steps.app-name.outputs.name }}" \
          --arg timeout "${{ inputs.timeout-seconds }}" \
          --arg port "${{ inputs.port }}" \
          --arg component_name "${{ steps.app-name.outputs.name }}:${{ github.sha }}" \
          --arg max_cpu "${{ inputs.max-cpu }}" \
          --arg max_memory "${{ inputs.max-memory }}" \
          --arg image "${{ inputs.container-registry }}/${{ steps.app-name.outputs.name }}:${{ github.sha }}" \
          --arg server "${{ inputs.container-registry }}" \
          --arg username "${{ inputs.container-registry-user }}" \
          --arg password "${{ inputs.container-registry-password }}" \
          --argjson env_vars "$ENV_VARS" \
          '{
            "name": $name,
            "timeout_seconds": ($timeout | tonumber),
            "port": ($port | tonumber),
            "min_scale": 0,
            "max_scale": 1,
            "components": [
              {
                "name": $component_name,
                "max_cpu": $max_cpu,
                "max_memory": $max_memory,
                "deploy_source": {
                  "container_registry": {
                    "image": $image,
                    "server": $server,
                    "username": $username,
                    "password": $password
                  }
                },
                "env": $env_vars
              }
            ]
          }')
        
        # Check if application already exists
        APP_NAME="${{ steps.app-name.outputs.name }}"
        EXISTING_APPS=$(curl -s -X GET \
          -H "Authorization: Basic ${AUTH}" \
          -H "Content-Type: application/json" \
          https://secure.sakura.ad.jp/cloud/api/apprun/1.0/apprun/api/applications)
        
        # Extract app ID if exists
        APP_ID=$(echo "$EXISTING_APPS" | jq -r ".data[] | select(.name == \"$APP_NAME\") | .id" || true)
        
        if [ -n "$APP_ID" ]; then
          echo "Updating existing application: $APP_ID"
          # Update existing application
          RESPONSE=$(curl -s -X PATCH \
            -H "Authorization: Basic ${AUTH}" \
            -H "Content-Type: application/json" \
            -d "${REQUEST_BODY}" \
            https://secure.sakura.ad.jp/cloud/api/apprun/1.0/apprun/api/applications/${APP_ID})
        else
          echo "Creating new application"
          # Create new application
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: Basic ${AUTH}" \
            -H "Content-Type: application/json" \
            -d "${REQUEST_BODY}" \
            https://secure.sakura.ad.jp/cloud/api/apprun/1.0/apprun/api/applications)
        fi
        
        # Extract values
        PUBLIC_URL=$(echo "$RESPONSE" | grep -o '"public_url":"[^"]*' | sed 's/"public_url":"//') || true
        APP_ID=$(echo "$RESPONSE" | grep -o '"id":"[^"]*' | sed 's/"id":"//') || true
        
        # Set outputs
        echo "public-url=${PUBLIC_URL}" >> $GITHUB_OUTPUT
        echo "app-id=${APP_ID}" >> $GITHUB_OUTPUT
        
        if [ -n "$PUBLIC_URL" ]; then
          echo "🚀 Successfully deployed to: $PUBLIC_URL"
        else
          echo "❌ Deployment failed"
          echo "$RESPONSE"
          exit 1
        fi